### ISSUE TITLE
Flickering issue

### ISSUE THREAD

**Issue by bguthrie1** [rdoeffinger/xwa_ddraw_d3d11#10] opened 2019-01-26 06:25 UTC
There seems to be some sort of flickering issue with the latest development. 

Here is a link to the video showing the issue: https://1drv.ms/v/s!AoEpIrw6LOkUjccrXpg7AEqFc9lAlQ

**Comment by rdoeffinger** [comment] 2019-01-26 09:51
Any idea since when? This kind of looks like standard Z fighting, which should not be affected by the kind of changes me or Jeremya have been doing.

**Comment by bguthrie1** [comment] 2019-01-26 09:56
It seems this doesn't happen with 1.5.7 for some reason.

**Comment by rdoeffinger** [comment] 2019-01-26 10:14
@JeremyAnsel this issue seems to go away for me if I revert the 16 bpp texture support. Can you confirm?
(to reproduce you can start a Skirmish in an A-Wing against a couple of buoys, numpad * to switch to external view, numpad / to be able to rotate the view - flickering engine lights I guess are intentional, but the border between the red and white part of the rear A-Wing part for some reason starts to flicker)

commit 0082089579764afc78aebc3330b365cfcc04b2e5
Author: Jérémy Ansel <JeremyAnsel@users.noreply.github.com>
Date:   Tue Jan 15 14:08:56 2019 +0100

    Add support for 16-bpp in texture loading

**Comment by rdoeffinger** [comment] 2019-01-26 10:36
Note: We are both running NVidia graphics. Since I think there might be a risk of this being some hardware/driver issue? Not overly likely I admit, but I don't have a good explanation for the issue otherwise.

**Comment by bguthrie1** [comment] 2019-01-26 10:55
The above ddraw fixed the issue on my end.

**Comment by JeremyAnsel** [comment] 2019-01-26 13:06
Strange, I haven't flickering issue with version 1.3.6 with either Intel or NVidia graphic card.
I've tested in skirmish with an A-Wing. The flickering engine glow is intentional.

**Comment by rdoeffinger** [comment] 2019-01-26 16:18
I don't understand it, sometimes the alpha value for 565 textures is 0, and it's not the border colour.
Either something is going on I don't understand or alpha for 565 textures is buggy on NVidia cards.

**Comment by rdoeffinger** [comment] 2019-01-26 17:02
[xwing_ddraw_d3d11_1.5.8_rc1.zip](https://github.com/rdoeffinger/xwa_ddraw_d3d11/files/2799249/xwing_ddraw_d3d11_1.5.8_rc1.zip)
Ok, if there are no more issues anyone spots, I think I'll make a release of that one...

**Comment by bguthrie1** [comment] 2019-01-31 21:19
Haven't seen the flickering issue so far. I think its ok to close this one.

**Comment by rdoeffinger** [comment] 2019-02-01 18:52
Ok, thanks, closing.

**Closed by rdoeffinger** 2019-02-01 18:52 UTC
