### ISSUE TITLE
X-Wing (1998) and TIE Fighter (1998) Run at 10 FPS with AMD Drivers Above 16.12.1

### ISSUE THREAD

**Issue by lemabr01** [rdoeffinger/xwa_ddraw_d3d11#2] opened 2017-01-28 01:56 UTC
When running TIE Fighter with the newest AMD 17.1.1. drivers the game runs at around half the speed it should.  This is with an RX 480.  Previously using the 16.12.1 drivers and this version saw no performance issues.  Switching back to the standard ddraw.dll fixed the issue, confirming it is an issue with the DirectX11  ddraw.dll and not the game in general.

Additional testing confirms that the AMD 16.12.2 drive also causes the same issue.

Note that this issue does not appear in X-Wing vs. TIE Fighter.  I was unable to test X-Wing Alliance.

To replicate:  Install the latest AMD drivers and run any mission in the Windows Collector Edition of TIE Fighter or X-Wing.  The FPS should be around 10 FPS even though the game should run at 30.

workaround: rolling drivers back to 16.12.1 resolves the issue.

**Comment by rdoeffinger** [comment] 2017-01-28 13:30
I don't have any graphics card supported by that driver version.
Does the issue show during gameplay and in the menu?
Also, have you made sure to enable 3D hardware in the graphics settings? Does changing the rendering mode (8-bit, 16-bit, 3D I think are the available options) make any difference?
Either way as it is a regression it might be best to report it to AMD.
Also note that the release notes mention numerous performance issues both fixed and known with borderless fullscreen, at least if you are using FreeSync compatible hardware: http://support.amd.com/en-us/kb-articles/Pages/Radeon-Software-Crimson-ReLive-Edition-16.12.2-Release-Notes.aspx
So you might want to try changing the configuration to use "proper" fullscreen or windowed (Fullscreen = 1 or Fullscreen = -1 in ddraw.cfg).

**Comment by lemabr01** [comment] 2017-01-28 15:54
-The menu is also slowed, yes.
-Changing rendering mode does not show a difference.  It is slowed on 3D hardware, 16 bit, etc.
-Switching to Fullscreen=1 or Fullscreen=-1 does appear to fix the issue. Not sure why that would fix it, is Fullscreen=0 a different rendering algorithm?

**Comment by rdoeffinger** [comment] 2017-02-11 15:08
The "Fullscreen" setting has nothing to do with rendering itself, it's only about where it is being rendered to.
Fullscreen=1 renders in a special, exclusive fullscreen mode. Kind of telling the OS "That monitor's mine, don't let anyone else touch it". That's how games used to be done decades ago, but it usually caused flickering and other bad effects when switching out of the program, (even worse) issues with game overlays etc. It basically is an outdated "hack".
-1 renders in a normal window. Like that, all the application switching etc. works just fine, but the scene needs to be combined with the rest of the desktop, which makes it slow, causes issues with vsync and of course you really don't want a game running in a window.
The default with which you have issues is supposed to solve all these problems: it is rendering to a window, but the window has no borders and covers the full screen, the way you want a game to look. However it still has some of the performance and vsync issues, so the drivers have special hacks to detect this case and whenever possible treat it like the old fullscreen mode, thus combining the advantages of both. That's the theory at least. It seems in practice however they put so many hacks in the drivers for this that the whole thing falls over and you get issues like yours. At least that seems a likely theory matching the symptoms.
At least if you are using a FreeSync monitor it sounds like the issue is known and if you are lucky it gets fixed at some point.

**Comment by PrinceOfJudah** [comment] 2017-06-24 21:46
I'm also getting horrible performance using a GTX 960m while using your dll. changing the fullscreen settings don't effect it.

**Comment by PrinceOfJudah** [comment] 2017-06-24 22:35
i seem to be capped at 24 fps and performance is awful.

**Comment by rdoeffinger** [comment] 2017-06-25 13:48
While it could be just a driver issue (especially for mobile GPUs, the notebook vendor drivers are often particularly horrible - assuming you use that), it could also just be that the GPU never goes out of power-saving mode due to the low load, in which case manually switching it to performance mode (if you find such an option) might help.
There is also a bit of an issue with the menu drawing that in some cases causes weird behaviour of various types, though 24 fps doesn't seem particularly bad for that part, gameplay is more relevant. Also note that the game is limited to 30 fps, if your screen is set to 50 Hz refresh that probably would end with it stuck at 25 fps, at least if vsync is on.

**Comment by rdoeffinger** [comment] 2019-01-26 10:32
Old ticket, and more performance fixes have been done. Many people achieve a stable 60 FPS. I'll close it, reopen or open a new one if there are still issues.

**Closed by rdoeffinger** 2019-01-26 10:32 UTC
