### ISSUE TITLE
My DXdiag

### ISSUE THREAD

**Issue by fetito666** [rdoeffinger/xwa_ddraw_d3d11#1] opened 2016-03-26 07:28 UTC
[DxDiag.txt](https://github.com/rdoeffinger/xwa_ddraw_d3d11/files/190383/DxDiag.txt)

**Comment by rdoeffinger** [comment] 2016-03-26 08:19
Related to slow 2D interface issue, see e.g. https://www.gog.com/forum/star_wars_xwing_and_tie_fighter_series/xwing_1998_very_slow

**Comment by rdoeffinger** [comment] 2016-04-09 09:30
Issue was determined to be caused by XBox controller driver update, so closing.

**Closed by rdoeffinger** 2016-04-09 09:30 UTC
